//ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const GET_COOKIES = "GET_COOKIES";
export const GET_COOKIES_SCAN = "GET_COOKIES_SCAN";
// export const ADD_COOKIES = "ADD_COOKIES";
export const RELOAD_IN_COOKIES = "RELOAD_IN_COOKIES";
export const CLOSE_UPDATE_MODAL = "CLOSE_UPDATE_MODAL";
export const OPEN_UPDATE_MODAL = "OPEN_UPDATE_MODAL";

//CATEGORIES
export const GET_OPTIONS_CATEGORIES = "GET_OPTIONS_CATEGORIES";
export const GET_LIST_CATEGORIES = "GET_LIST_CATEGORIES";
export const RELOAD_IN_CATEGORIES = "RELOAD_IN_CATEGORIES";

//USERS
export const GET_USERS = "GET_USERS";
export const RELOAD_IN_USERS = "RELOAD_IN_USERS";
export const GET_ALL_USERS_EXPORT = "GET_ALL_USERS_EXPORT";
export const GET_OPTIONS_CATEGORIES_IN_USERS =
  "GET_OPTIONS_CATEGORIES_IN_USERS";

//SETTINGS
export const GET_SETTINGS = "GET_SETTINGS";
export const REMOVE_TAG = "REMOVE_TAG";
export const ADD_TAG = "ADD_TAG";
export const RELOAD_IN_SETTINGS = "RELOAD_IN_SETTINGS";
export const SAVE_SETTINGS = "SAVE_SETTINGS";
// export const RESET_ARR_COUNTRIES = "RESET_ARR_COUNTRIES";
